### PR TITLE
[16.0][FW] payroll_account: Fix multicompanies and refactoring (port of #121 and #123)

### PR DESCRIPTION
**Pull request by norlinhenrik**
Port of #121 and #123 from 15.0 to 16.0

### CODE REVIEW

**Comment by nimarosa** [comment]
@norlinhenrik please check tests to move forward

**Comment by norlinhenrik** [comment]
Done

**Comment by norlinhenrik** [comment]
payroll_account/models/hr_payslip.py is split into one file per model.

hr.salary.rule `account_debit` & `account_credit` has got `company_dependent=True`.

Can we merge this?

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Hello sorry for the late review. I'm busy weeks. 

Checked the code and tested in run boat, everything seems fine.

We can merge.

/ocabot merge nobump

**Pull request merged**
