### PR TITLE
[13.0][MIG] payroll_account from odoo v12

### PR DESCRIPTION
**Pull request by Saran440**
Migrated from odoo v12 and fixed test script

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm thinking that we have a problem with the module name. We should switch to `hr_payroll_oca` for avoiding the collapsing with enterprise one.

**Comment by Saran440** [comment]
Should module name `hr_payroll_account_oca`?
because this module extended to accounting

**Comment by pedrobaeza** [comment]
Yes, it would follow the same path, but we should start with the base one. Another option is `payroll` or `payroll_mgmt`.

**Comment by FernandoRomera** [comment]
My vote is for: payroll, same name that the repo.

**Comment by usmanfarzandali** [comment]
> My vote is for: payroll, same name that the repo.

me too

**Comment by Saran440** [comment]
Finally, This module will name `payroll_account`
and module hr_payroll (OCA) https://github.com/OCA/payroll/tree/13.0/hr_payroll
will change name to `payroll`, right?

**Comment by pedrobaeza** [comment]
Yes, that's the idea. Can you please perform the renaming?

**Comment by FernandoRomera** [comment]
Following pedro's comment, you can add the file .pot. (same that in #8).

**Comment by FernandoRomera** [comment]
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#directories

Can you rename the "data" directory to "demo"?

**Comment by Saran440** [comment]
@FernandoRomera Thank you for your reviewed.
Change name and Fixed test script.

**Review by FernandoRomera — APPROVED** [review]
Functional review, ok.

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]

**Review by davejames — APPROVED** [review]
Functional review :+1:

**Comment by FernandoRomera** [comment]
@pedrobaeza Can you merge?

**Comment by pedrobaeza** [comment]
Can you please squash commits? I also miss the initial commit as it was in Odoo (without changes) and with neutral committer email like info@odoo.com.

**Comment by Saran440** [comment]
@pedrobaeza Should I squash to 3 commits or 4? (1 commit is change name, should be squash?)

**Comment by pedrobaeza** [comment]
Selección_015

**Comment by Saran440** [comment]
@pedrobaeza Done, Thank you for your advised. :)

**Pull request merged**
