### PR TITLE
[14.0][MIG] hr_payroll_cancel

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Migrate module to 14.0 from hr repository

This module allows the user to cancel a payslip whatever the previous state is
without doing a refund. When the user cancel the journal entry is deleted
and  the payslip state is set to rejected. Then the user is able to set the
state to draft again and later on he/she is able to confirm again the payslip.

If there’s a refund for a payslip the user should not cancel the entry because
the refund would still be confirm. In that case, the user have either to
confirm again the payslip or cancel the refund.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @JuanyDForgeflow I cannot see the cancel button after a payslip is confirmed: http://oca-payroll-14-0-pr32-97f473182362.runboat.odoo-community.org/web#id=1&action=231&model=hr.payslip&view_type=form&cids=&menu_id=139

I think it should show. Can you check?

**Comment by nimarosa** [comment]
@JuanyDForgeflow Test for this are failing, please check. The error it's giving runbot "You must post a line before canceling". 

Otherwise, could you explain more the usage of this?

**Comment by nimarosa** [comment]
Please check that you always get this error when payslip cancels 
`odoo.exceptions.UserError: You need to add a line before posting.
`

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Review by MiquelRForgeFlow — COMMENTED** [review]
Eficent -> ForgeFlow

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
