### PR TITLE
[14.0][MIG] hr_payslip_change_state

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module process payslip batches:

* This module allows to mass change Payslip states
* The module checks if the required action is allowed for each payslip
* If any of the payslips are not in a suitable state a warning message will
  pop up and no changes will be made

### CODE REVIEW

**Comment by nimarosa** [comment]
+1 in migrating this module. Hope to see it soon.

**Comment by mtelahun** [comment]
Travis is failing. From the logs it seems like it's a simple mistake in importing a parent test class.

**Comment by MiquelRForgeFlow** [comment]
something seems wrong with commit history. why hr_payroll_cancel commits are there?

**Comment by nimarosa** [comment]
@MiquelRForgeFlow Probably because someone updated both modules in the same commit? I think... Maybe you can extract the folder.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]
For me it's okay

**Comment by nimarosa** [comment]
@pedrobaeza This is ready to merge too.

**Pull request merged**
