### PR TITLE
[16.0][ADD] hr_payroll_document: New module hr_payroll_document

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by peluko00** [comment]
The hr_payroll_document module manages the payroll for each employee and combines the pages on which the identification number of employee appears. The pdf is sent to the employee who can open it with their identification number because it is encrypted.

cc https://github.com/APSL 145523

@miquelalzanillas @lbarry-apsl @javierobcn @samoros1 please review

**Review by miquelalzanillas — APPROVED** [review]

**Comment by nimarosa** [comment]
Tests are failing for this PR. Please check that and rebase it to the base branch.

**Comment by peluko00** [comment]
> Tests are failing for this PR. Please check that and rebase it to the base branch.

Payroll module failing, in that [line](https://github.com/OCA/payroll/blob/16.0/payroll/tests/test_payslip_flow.py#L238)
[This](https://github.com/OCA/payroll/pull/143) pr fix the problem with the test

**Comment by peluko00** [comment]
> > Tests are failing for this PR. Please check that and rebase it to the base branch.
> 
> Payroll module failing, in that [line](https://github.com/OCA/payroll/blob/16.0/payroll/tests/test_payslip_flow.py#L238).
[This](https://github.com/OCA/payroll/pull/143) pr fix the problem with the test

**Comment by nimarosa** [comment]
#143 is being merged. Please @peluko00 rebase this PR when this is merged so we can continue.

**Comment by peluko00** [comment]
> #143 is being merged. Please @peluko00 rebase this PR when this is merged so we can continue.

Done! Review please

**Review by samoros1 — COMMENTED** [review]
Functionality checked!

**Comment by peluko00** [comment]
> Functionality checked!

Please approve

**Review by samoros1 — APPROVED** [review]
Functionality checked!

**Review by javierobcn — APPROVED** [review]
Checked, runs perfect!

**Pull request merged**
