### PR TITLE
[16.0] [MIG] payroll_hr_public_holidays: Migration to version 16.0

### PR DESCRIPTION
**Pull request by nimarosa**
Standard migration.

### CODE REVIEW

**Comment by nimarosa** [comment]
**This PR has to wait the migration of oca/hr_holidays_public to be merged.**

**Comment by nimarosa** [comment]
Will open new PRs with new migrations.

**Comment by peterromao** [comment]
Hello nimarosa,
I am not very good with this commits and PR's but I went through the code and there doesn't seem to be any reason why this shouldn't be in the 16.0 lineup of modules.
Is only an administrative thing needed to push this?
I would help just don't know how. Most I can do is setup a local odoo install and mock up a 16.0 version of this module and come back here and say it works or not.
Thank you

**Pull request closed without merging**
