### PR TITLE
[14.0] [IMP] Improve account view to match salary_rule form UX

### PR DESCRIPTION
**Pull request by nimarosa**
Since OCA don't allow changes in more than one module per PR. Here i have a small change to the salary_rule views of accounting fields. 

Thanks.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
I think the commit messages should start with `payroll_account:`
`payroll_account: add nimarosa to maintainers`

**Comment by nimarosa** [comment]
Changed commit messages according the rules. Can we merge that? 
@appstogrow @pedrobaeza

**Comment by pedrobaeza** [comment]
Not the second commit... and it's preferable to leave an space between `[IMP]` and the module name.

**Comment by nimarosa** [comment]
@pedrobaeza whats wrong to the second commit? The space was a typo error will update commit message now

**Comment by pedrobaeza** [comment]
Selección_007

**Comment by nimarosa** [comment]
@pedrobaeza haha okay. I did not put IMP because that commit is not particularly an improvement. But will change it. 

Sorry about the errors, all the last 4/5 PRs I have made to the repo are my first PRs to OCA and have to adapt to the guidelines, which are different in every project. 

Thanks, will change in a few hours and let you know.

**Comment by pedrobaeza** [comment]
Don't worry, and it's understandable your logic. The question is that the format should be fixed. Now, what to put between brackets? Putting you as maintainer can be considered as an improvement, as now the module is not orphaned :smile:

**Comment by nimarosa** [comment]
@pedrobaeza 

Ready to merge (Y). Also check the other PR that @appstogrow give you the ok to merge. It will be great if we merge this 2 PR now so i can start with another PRs that i have been working on. 

Thanks Pedro.

**Pull request merged**
