### PR TITLE
[FIX] Payslip item name in user interface language.

### PR DESCRIPTION
**Pull request by kasado**
When computing payslip, generate payslip line name in user interface language.

### CODE REVIEW

**Comment by kasado** [comment]
> Hi @nimarosa, @appstogrow, some modules you are maintaining are being modified, check this out!

Quick question, could you please review the PR? Just wondering if you are using payroll, have you noticed that payslip items are not translated to user language?

regards
Kasparas

**Comment by nimarosa** [comment]
Hello @kasado i don't see any changes in code, only a change in one file adding a line break. Please be sure the PR is complete.

**Comment by kasado** [comment]
> Hello @kasado i don't see any changes in code, only a change in one file adding a line break. Please be sure the PR is complete.

Hi Nicolas,

Threre are two commits in PR. Please look on the first one a087ea.... Just adding context calling call_kw. Second one commit was simply to split same line, because it failed some pre_submit test. 

Regards
Kasparas

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
