### PR TITLE
[14.0][MIG] payroll_account: Migration to 14.0

### PR DESCRIPTION
**Pull request by ghost**
Nothing to update

### CODE REVIEW

**Comment by ghost** [comment]
Travis error:

ERROR: Could not find a version that satisfies the requirement odoo14-addon-payroll (from odoo14-addon-payroll-account) (from versions: none)

ERROR: No matching distribution found for odoo14-addon-payroll

How to run the checks again now after payroll is merged?

**Comment by pedrobaeza** [comment]
Until tomorrow the package won't be available, and then the builds should be retriggered.

**Comment by AntoniRomera** [comment]
Good when you can redo the PR, also if you can look at the PR #16  that adds the functionality to put the whole issue of withholdings when creating the accounting entry.

**Comment by ghost** [comment]
@AntoniRomera I suggest first approve #21, then based on #16 you can make a new PR. I will also make a new PR with suggestions for improvements.

**Review by FernandoRomera — APPROVED** [review]

**Review by FernandoRomera — COMMENTED** [review]
Rename file and class to accomodate to new name:

test_hr_payroll_account.py => test_payroll_account.py
class TestHrPayrollAccount => class TestPayrollAccount

**Review by AntoniRomera — APPROVED** [review]

**Comment by AntoniRomera** [comment]
@apps2grow Travis red, Can you review it so that the merge can be done?

**Comment by AntoniRomera** [comment]
@apps2grow You can fix the pre-commit and I think you will be ready to merge.

**Comment by AntoniRomera** [comment]
@pedrobaeza Can you do the merge? I see that everything is ok, can you put the default branch 14?

**Comment by pedrobaeza** [comment]
The commit history is dirty. Please don't include merge commits here. I think you have to rebase instead of pulling, and resolve conflicts when they happen.

**Comment by AntoniRomera** [comment]
@appstogrow Can you clean the commit history?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Avoid merge commits

**Comment by ghost** [comment]
I resolved the conflicts, but it was not saved.
In every case, the second option is the correct option.

**Comment by AntoniRomera** [comment]
@pedrobaeza 
Is ok for you?
If you can merge, we could continue to add account taxes. Another pass to realize is change default branch to 14.

**Comment by pedrobaeza** [comment]
There are conflicting files, so the rebase hasn't been correct.

**Comment by ghost** [comment]
I cloned the repo again, copied payroll_account into the repo, and made a new commit replacing all the others. But then the history is not preserved. I will do it again, following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14%2E0

**Comment by pedrobaeza** [comment]
Superseded by #25

**Pull request closed without merging**
