### PR TITLE
14.0 mig payroll

### PR DESCRIPTION
**Pull request by hilarak**
Migration to version 14.0 #6 Payroll

### CODE REVIEW

**Comment by hilarak** [comment]
@davejames Please check, if anything needs to be updated please let me know.

**Comment by TheCloneMaster** [comment]
Checked, only small issue is please update hr_payslip.py with latest changes in V13 (replaced get_contract with native get_contracts from Odoo available since v13)

**Comment by TheCloneMaster** [comment]
Great!
Tested and works as expected

**Comment by hitrosol** [comment]
it's been a while since last tested. Any plan to merge this ?

**Review by nimarosa — APPROVED** [review]

**Comment by mtelahun** [comment]
Can someone please merge this so we can update with latest 13.0 changes?

**Comment by pedrobaeza** [comment]
Please squash your migration commits into one (leaving `[IMP] payroll: black, isort, prettier` untouched).

**Comment by norlinhenrik** [comment]
@hilarak Thank you for doing the migration. Please see the comment from @pedrobaeza

**Comment by norlinhenrik** [comment]
@hilarak Would you like to squash your migration commits? Or should I take over and make a new PR?

**Comment by hilarak** [comment]
Please go ahead. :)

**Comment by norlinhenrik** [comment]
([hr.payslip _get_payslip_lines()](https://github.com/OCA/payroll/blob/13.0/payroll/models/hr_payslip.py#L409)) has more than 100 lines of code. For version 12.0 I made a [patch](https://github.com/apps2grow/apps/blob/12.0/hr_rule_qty_rate_amount/hr_payroll-core-changes.patch#L45) to make a payslip line for each analytic account defined for a hr.salary.rule. So I would like to squash the previous migration commits, and then add a new commit for this. Or should I rather make another PR specifically for this?

**Comment by mtelahun** [comment]
Hi Henrik,

My own preference would be for the migration first and the improvements 
in a separate PR.

**Comment by norlinhenrik** [comment]
I plan to create migration PR on Sunday. After merging, I will propose improvement PR.

**Pull request closed without merging**
