### PR TITLE
[13.0][FIX] payroll: add group migration

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
When https://github.com/OCA/payroll/pull/23 was done, they forgot to add this:
Selection_2380

Also, as the module is renamed to payroll in https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/addons/openupgrade_records/lib/apriori.py#L95, all xmlids should begin with `payroll.` to be found.

**_Note:_** merge with nobump.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@nimarosa @pedrobaeza @victoralmau

**Review by nimarosa — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is red. This can be switched to GH actions.

**Comment by MiquelRForgeFlow** [comment]
Ready to merge

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
