### PR TITLE
[14.0][IMP] payroll: Show the newest payslip and payslip batch (id desc). Payslip line with date_from.

### PR DESCRIPTION
**Pull request by ghost**
This PR will order hr.payslip and hr.payslip.run by "id desc" to show on top the records that were most recently created.

### CODE REVIEW

**Comment by ghost** [comment]
date_from field on hr.payslip.line is very useful for pivot.

**Comment by nimarosa** [comment]
Hello @appstogrow great feature. It gives a lot of usefulness to the pivot table. 

Please rebase and fix the commit history and we merge it fast.

**Comment by mtelahun** [comment]
Hi @appstogrow , I'm assuming this is because newly created payslips that haven't been computed yet will now display at the head of the list. Am I correct? I'm just wondering if I missed something.

Also, does the addition of the date field to the payslip line fit in with the rest of this PR?  "date_from field on hr.payslip.line is very useful for pivot" tells me why that particular change is an improvement, but I don't understand how it fits in with this PR. I understand if it's a small change that doesn't warrant it's own PR, but in that case could it be a separate commit please?
Thanks.

**Comment by nimarosa** [comment]
We can do two commits with description of each change in this PR. I don't think we have to open a new PR for every change, since this is a simple but useful one. Two commits in the PR will do the trick. 

I tested it and it's working in local environment. 

Just clean the commit history of your branch @appstogrow with a rebase and for me we are okay. 

Let's get this merged before i open my refactoring PR so we include this changes and i can rebase.

**Review by nimarosa — APPROVED** [review]

**Comment by ghost** [comment]
@mtelahun Yes I want to see on top the payslips that were created most recently, because I edit them manually.

I have made a separate commit for the hr.payslip.line with date_from. It is not related to the "order by id desc".

Separate commits are useful for history, and for cherry-pick. Are separate commits useful for other things also?

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Great, we merge this so I can rebase refactor branch and submit new PRs today. 

/ocabot merge minor

**Comment by mtelahun** [comment]
@appstogrow Thank you. As you said separate commits are useful for history. In addition to keeping each commit clean (i.e- only changes related to the functionality addressed in the commit) they make using git bisect easier.

**Comment by ghost** [comment]
[git-bisect - Use binary search to find the commit that introduced a bug](https://git-scm.com/docs/git-bisect)
Must be a very useful git command - I never heard of it before!

**Pull request merged**
