### PR TITLE
[14.0][MIG] payroll

### PR DESCRIPTION
**Pull request by ghost**
This PR is based on https://github.com/OCA/payroll/pull/11
payroll/i18n is copied from https://github.com/OCA/payroll/pull/18

### CODE REVIEW

**Comment by hitrosol** [comment]
hi @apps2grow, I can't find the runbot of this PR, therefore I try this on my local. 
I found the error message when I try to confirm the Employee Paysllp. 

image

I found that's because the salary rules wasn't set correctly.  There is no **Python Code** field whenever we select the **Amount Type**
image



Hopefully we can fix and merge this repo, so the community will have option since the payroll has been moved to EE since V12.

**Comment by hitrosol** [comment]
I try this on local and the python code already shown as expected. 
Anyone know why there is no runbot link in this PR ?

**Comment by FernandoRomera** [comment]
@apps2grow Can you force a pull to run new tool runboat?

https://twitter.com/i/status/1467143393054797826

**Review by FernandoRomera — APPROVED** [review]
Test in local, OK.

**Review by AntoniRomera — APPROVED** [review]

**Comment by FernandoRomera** [comment]
Please @pedrobaeza can you review it?

**Comment by pedrobaeza** [comment]
/ocabot migration payroll

Merging trusting on your reviews:

/ocabot merge nobump

**Pull request merged**
