### PR TITLE
[17.0][MIG] payroll: Migration to 17.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by mtelahun** [comment]
Please follow the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

Specifically, please ~~remove~~ squash the administrative commits made by ocabot.

**Comment by hieulucky111** [comment]
I am doing some functional tests and here is my first problem
When i save the payslip, the structure is gone.
image
image

**Comment by hieulucky111** [comment]
Display of Generates Payslip Batch Wizard is not good
image

**Comment by celm1990** [comment]
Hi, @FernandoRomera  could you please comment on the status of this PR? I am interested in contributing to the migration.

**Comment by hapolinario** [comment]
superseded by https://github.com/OCA/payroll/pull/142

**Pull request closed without merging**
